version: '3'
services:
  app:
    container_name: koopa
    tty: true
    build: .
    command: npm run start
    ports:
      - '3000:3000'
    external_links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db